### ISSUE TITLE
Class "Mguinea\Robots\Facades\Robots" not found

### ISSUE THREAD

**Issue by mwagner** [mguinea/laravel-robots#18]
I was following your installation instructions, but when loading the route 'robots.txt' it returns the error 
`Class "Mguinea\Robots\Facades\Robots" not found
`
I'm running Laravel 11.23.5 (PHP v8.3.11)

**Comment by mguinea** [comment]
Fixed, ensure that the version is at least 3.1.4

**Comment by mwagner** [comment]
Thank you for the fix, it's working now
