### ISSUE TITLE
Class 'Robots\RobotsServiceProvider' not found

### ISSUE THREAD

**Issue by alejog1582** [mguinea/laravel-robots#5]
Al realizar la instalacion en laravel genera este error. In ProviderRepository.php line 208:

  Class 'Robots\RobotsServiceProvider' not found

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.

**Comment by mguinea** [comment]
He subido la versión 3.0.2 donde está corregido el error. ¡Gracias!

**Comment by alejog1582** [comment]
Muchas gracias ya me instalo correctamente
